### ISSUE TITLE
[Standardised] Some of the rows in merged table are not students, don't have values in Acad Prog

### ISSUE THREAD

**Issue by dhuy228** [UoA-eResearch/cie-student-activity#10]
Dump into csv and send it to Darsel

**Comment by DarselK** [comment]
There are external people who do our programmes. The plan had be to have them come up as external in all of the visualisations (gender, ethnicity, programme etc). That way our numbers would reflect the total.

**Comment by dhuy228** [comment]
These people appear as students in the files, potentially they have used fake IDs. 

Count: **2,295** people in total.

**Comment by DarselK** [comment]
The truth in regards to whether they are students, or not, comes from the files from Rachel. This data is pulled from the UoA student services online system. If they are not in there, they are not students. Which file(s) are they coming from? Given the high number I suspect that they are staff, alumni, external

**Comment by DarselK** [comment]
Is this one resolved?

**Comment by dhuy228** [comment]
All these rows will be classified as NAs. Look at #67
