### ISSUE TITLE
[Standardised] Tags should be sorted by date in order to create the journey.

### ISSUE THREAD

**Issue by dhuy228** [UoA-eResearch/cie-student-activity#11]
Darsel can provide date data for each of the tag so they could be sorted

**Comment by DarselK** [comment]
I am working on this. Will send through asap

**Comment by dhuy228** [comment]
Link https://www.dropbox.com/s/tgtcyrvnljg80v9/tags%20from%202015%20-%202019%20CIE%20Participant%20dataset.xlsx?dl=0
