### ISSUE TITLE
[Standardised] "Student" naming sheet is not consistent. Replace "Students" with "Student"

### ISSUE THREAD

**Issue by dhuy228** [UoA-eResearch/cie-student-activity#14]

**Comment by DarselK** [comment]
Hello, to clarify - is this a change for the future or would you like me to update in the existing excel files?

**Comment by dhuy228** [comment]
Hi Darsel, this is a change for the future. I already updated in the existing files.

**Comment by DarselK** [comment]
I think this one is resolved?
