### ISSUE TITLE
[Standardised] Conjoint students appear more than once

### ISSUE THREAD

**Issue by dhuy228** [UoA-eResearch/cie-student-activity#16]
for different values in `Acad Plan`, `Plan Description`

**Comment by dhuy228** [comment]
Don't have data to show in specific year, which program the student is in

**Comment by DarselK** [comment]
The data has been run by year so the data that is presented in 2015 is the programme(s) the student was enrolled in for that year. This will change over the years. Either as student changes programme or major and / or moves onto a higher degree. 

With the multiple entries. In the 2017 from Rachel file there is ID 506258588 that is 5 times. Each of these 5 entries relate to a different 'Plan Description. For this ID number it is Marketing, Operations & Supply Chain   Mgmt, Management, Property, Information Systems
