### ISSUE TITLE
[Bugs] Some students don't have `CIE participant` tag.

### ISSUE THREAD

**Issue by dhuy228** [UoA-eResearch/cie-student-activity#21]
Example:

ID 5299005 has 2019 Unleash Space Access but no CIE Participant tag

In 2016 dataset,

`Tags`: Weekly   Newsletter,Unleash Space,2016 CIE Participant,Unleash Space   Newsletter,Unleash Space Participant,2016 Velocity Innovation Seminar   Participant,Velocity,2016 Velocity Agritech Seminar Participant,2016 Velocity   Participant,Unleash Space Newslettter,2019 Unleash Space Access
--

**Comment by dhuy228** [comment]
NOTE FOR ME:

To do the error diagnosis, apply pivot table to all.csv, with this stetting

![image](https://user-images.githubusercontent.com/30312302/65106061-8ff21780-da2a-11e9-997e-49e955552f03.png)

**Comment by dhuy228** [comment]
Solution suggestion

Create a separate table programmeOverachingProgramme

**Comment by dhuy228** [comment]
Some students have `CIE Participant` tag in that year but do not have any other tags.

Ex: 

102981585 | 2018 | CIE Participant

**Comment by dhuy228** [comment]
This is because the tags are not consistent in the selection.xlsx. Tags is `Equipment Training` which should be `Equipment Training Participant`

**Comment by dhuy228** [comment]
This is noted in the `Final Tag Format` column in tags-selection.xlsx

**Comment by DarselK** [comment]
I suspect that this is going to be an issue with other tags, for example Year Velocity Participant not being added consistently to all Velocity activities. This is an issue for the dashboards and also for the data source. As data will be continually added to the dashboard, from the data source I need to make sure that this is corrected as well. Is there a way to update the tag in dashboard quite easily and quickly (you seemed to have with YEAR CIE Participant) and also to identify which ones were missing so I can update them in the data source?
