### ISSUE TITLE
[Standardised] Rename Faculty names

### ISSUE THREAD

**Issue by dhuy228** [UoA-eResearch/cie-student-activity#33]
"There is duplication in the Faculties. I am little concerned about this as the Faculty information should be pulled from the UoA data (from Rachel). I thought this data had a very specific and consistent way of reporting which would prevent this from happening. Is this not the case? How best to resolve this and do you need me to send detail on which ones to combine?"

- Darsel to rename faculty names in a separate .csv file. Similar to **tags_selection.xlsx**,  include columns **faculty**, **final_faculty**

**Comment by DarselK** [comment]
Thanks David. I will send an email with the ones that need to be merged. I will also look at the source data to see if I can identify the core issue. For ongoing updating and uploads to the dashboards there will need to be a way to build this in to the process the make it simple and streamlined.

**Comment by dhuy228** [comment]
Most of these duplicated faculties name are from 2015
