### ISSUE TITLE
[CIE Overview Dashboard] Remove some programmes

### ISSUE THREAD

**Issue by dhuy228** [UoA-eResearch/cie-student-activity#36]
o	2015 - remove MCE Cohort and PhD Programme Participant
o	2016 - remove Velocity Vision to Business Participant, Velocity Innovate 2 Business Participant, Velocity Innovation Seminar Participant, Velocity $100K/k Qualifier Participant (these are the same programme and should be combined), and MCE Cohort. Could we please add Velocity $100K Participant and Velocity Participant
o	2017 - remove Create and Make Space Workshop Participant and Create and Make Workshop Participant (this data is the same programme and should be combined on Unleash Space and Create and Maker Space Dashboard), Velocity Vision to Business Participant, Velocity Innovation Seminar Participant, Velocity Innovate 2 Business Participant, Velocity $100k Qualifier, PhD Programme Participant, MCE Cohort, Innovation Squad Participant, Equipment Training Soldering an Desoldering Participant, Equipment Training Participant, Climathon Participant, Bespoke Faculty Programme Participant, Unleash Space Access
o	2018 - remove Unleash Space Access, Equipment Training Participant / Equipment Training (should be combined in other dashboards as same programme), Technology Trends Speaker Series Participant / Technology Trends Series (should be combined in other dashboards as same programme), Create and Make Workshop Participant / Unleash Space Create and Make Space Workshop Participant (should be combined in other dashboards as same programme), Founder Series Participant / Founders Series (should be combined in other dashboards as same programme), Velocity Innovate 2 Business Participant, Startup School Participant, Velocity $100k Qualifier Participant, MCE Cohort, Innovation Squad Participant, Equipment Training Soldering an Desoldering Participant
o	2018 - remove Create and Make Workshop Participant / Unleash Space Create and Make Space Workshop Participant (should be combined in other dashboards as same programme), Technology Trends Speaker Series Participant, Startup School Participant, MCE Cohort. There will be some offerings added to this when we update with the next lot of 2019 data.

**Comment by DarselK** [comment]
Hi David, I see this has been assigned to me. Happy to update in dashboards but not sure if I know how? Any chance I can either come to you for a lesson or is there someone else I can learn the steps. Thanks :)

**Comment by dhuy228** [comment]
Hi Darsel, this will be done in **tags_selection.xlsx**

To combine different programmes to one, you can change the final tag of the programme you want to remove to the programme you want to combine.

To remove the programme tag from the dashboard, you can easily change **"Y"** to **"N"** in the column with dashboard name.

Hope that helps and please let me know if you have further questions :) Ryan

**Comment by DarselK** [comment]
Where can I find the file?

**Comment by dhuy228** [comment]
Sorry, I renamed the original exel file from **tags from 2015 - 2019 CIE Participant dataset.xlsx** to **tags_selection.xlsx**. It should be the **tags from 2015 - 2019 CIE Participant dataset.xlsx** file in Dropbox (Capsule and Power Bi > Tags)

**Comment by DarselK** [comment]
The spreadsheet is now all updated :)

**Comment by dhuy228** [comment]
Uploaded the new updated spreadsheet
