### ISSUE TITLE
[Standardised] In `Owner.of.Major.Spec.Module`, Need rules to control the field requirements 

### ISSUE THREAD

**Issue by dhuy228** [UoA-eResearch/cie-student-activity#4]
There are values called New Start, The University of Auckland. Need rules to control the field requirements

**Comment by dhuy228** [comment]
New start = keep

The University of Auckland = Tertiary Education

**Comment by DarselK** [comment]
Is there anything outstanding on this one?

**Comment by DarselK** [comment]
Is this one resolved?
