### ISSUE TITLE
[CIE Programme Dashboard] Department Split

### ISSUE THREAD

**Issue by dhuy228** [UoA-eResearch/cie-student-activity#41]
Too many values for Department field i.e. **Plan Description**

Hard to fit in the dashboard

**Comment by DarselK** [comment]
I am wondering if there is another way to present this data. I will need to think it through more, but for example could we do by Faculty and then Department? So if we were looking at One of the tags we could then select Faculty and then department come up? Does this make sense? Would it work?

**Comment by dhuy228** [comment]
Yes, it is possible because Department is a sub group of Faculty. In this case, it would be good to take a step back and find out what insights you want to get by splitting by Department. There are other ways to visualise Department fields despite the number of values.

I should have elaborated more in the last comment; I wasn't sure if **Plan Description** in Excel files describes **Department**. From looking at it, it seems like they're just majors. Is that correct?
