### ISSUE TITLE
[CIE Programme Dashboard] Affiliation split

### ISSUE THREAD

**Issue by dhuy228** [UoA-eResearch/cie-student-activity#43]
which field is Affiliation?

**Comment by DarselK** [comment]
Hi Ryan, 

This document may help? https://www.dropbox.com/s/acspgqjbrivxsbh/Matching%20Data%20from%20UoA%20to%20Capsule.docx?dl=0

This matches the fields in Capsule to the data received from Rachel / UoA. Affiliation is Programme Level. Affiliation in the data from Rachel / UoA is undergraduate, postgraduate, doctorate nonformal (column O in student sheet) etc. In addition to this, in the Capsule data there is University of Auckland Academic Staff staff, University of Auckland Professional Staff, Friend and Supporter of the University, Sponsor of Velocity. The data needs to be pulled from both the Rachel and Original files

**Comment by dhuy228** [comment]
Thanks Darsel

**Comment by dhuy228** [comment]
Affiliation is a sub group of Degree
